#!/bin/bash
CSTATUS=$(acpi -b | awk '{print $3}' | sed 's/,//g')
PERCENT=$(acpi -b | awk '{print $4}' | sed 's/[^0-9]//g')
TIMEREM=$(acpi -b | awk '{print $5}' | sed 's/,//g')

COLOR='\033[1;32m'
NOCOL='\033[0m'

if [[ ! $CSTATUS =~ Dis.* ]] 
then
    echo -e "${COLOR}$CSTATUS${NOCOL}"
else
    CSTATUS=
    [[ $PERCENT -le 80 ]] && CSTATUS=
    [[ $PERCENT -le 55 ]] && COLOR='\033[1;33m' && CSTATUS=
    [[ $PERCENT -le 30 ]] && COLOR='\033[1;33m' && CSTATUS=
    [[ $PERCENT -le 10 ]] && COLOR='\033[1;31m' && CSTATUS=
    echo -e "${COLOR}$CSTATUS  $PERCENT% [$TIMEREM]${NOCOL}"
fi
