#!/bin/sh

options="\
logout
refresh dwm
lockscreen
reboot
poweroff"

choice="$(echo "$options" | dmenu | cut -f 1 -d ' ')" || exit 1

case $choice in
    lockscreen)
        lockscreen
        ;;
    logout)
        kill -TERM $(pidof s dwm)
        ;;
    refresh)
        kill -HUP $(pidof s dwm)
        ;;
    reboot)
        reboot
        ;;
    poweroff)
        poweroff
        ;;
esac
