#!/bin/sh
cat $HOME/.local/share/gruvbox-dark.colors | dmenu -l 10 | awk '{print $2}' | xclip -i -sel c -f | xclip -i -sel p
[ ! -z $(xclip -o -sel p) ] && notify-send "$(xclip -o -sel p) copied to clipboard"
