#!/bin/sh

OPTIONS="Poweroff\nReboot\nSuspend\nHibernate\nLock"

case "$(printf $OPTIONS | dmenu -sb "#d3869b" -p "Exit options")" in
    Poweroff) systemctl poweroff ;;
    Reboot) systemctl reboot ;;
    Suspend) systemctl suspend ;;
    Hibernate) systemctl hibernate ;;
    Lock) lock-screen
esac
