#!/bin/bash

# Poll every 1 second
POLL=1

keyhelp(){
    echo -e "\n(q) quit; (r) reset maxes\n"
}

clear

CARD_NAME=$(sudo lshw -quiet -C display 2>/dev/null | grep "product" | sed 's/.*product: //g')
SCLKMAX=0
MCLKMAX=0
VOLTMAX=0
POWRMAX=0
FANMAX=0
TEDGMAX=0
TJNCMAX=0
TMEMMAX=0

#SCLKAVG=$(awk -F, 'NR>1 {sum+=$1; count++;} END {printf "%4.1f\n", sum/count}' $logfile)

while true ; do
    clocks=$(sudo tail -n15 /sys/kernel/debug/dri/0/amdgpu_pm_info | head -n11)
    temps=$(sensors)

    MCLK=$(echo "$clocks" | grep "(MCLK)" | sed 's/[^0-9.]*//g')
    SCLK=$(echo "$clocks" | grep "(SCLK)" | sed 's/[^0-9.]*//g')
    VOLT=$(echo "$clocks" | grep "(VDDGFX)" | sed 's/[^0-9.]*//g')
    POWR=$(echo "$clocks" | grep "(average GPU)" | sed 's/[^0-9.]*//g')

    FAN=$(echo "$temps" | grep -e "^fan1" | cut -f 1 -d "(" | cut -f 2 -d ":" | sed 's/[^0-9.]*//g')
    TEDG=$(echo "$temps" | grep -e "^edge" | cut -f 1 -d "(" | cut -f 2 -d ":" | sed 's/[^0-9.]*//g')
    TJNC=$(echo "$temps" | grep -e "^junc" | cut -f 1 -d "(" | cut -f 2 -d ":" | sed 's/[^0-9.]*//g')
    TMEM=$(echo "$temps" | grep -e "^mem" | cut -f 1 -d "(" | cut -f 2 -d ":" | sed 's/[^0-9.]*//g')


    # Update max values for stats
    (( $(echo "$SCLK > $SCLKMAX" | bc -l) )) && SCLKMAX=$SCLK
    (( $(echo "$MCLK > $MCLKMAX" | bc -l) )) && MCLKMAX=$MCLK
    (( $(echo "$VOLT > $VOLTMAX" | bc -l) )) && VOLTMAX=$VOLT
    (( $(echo "$POWR > $POWRMAX" | bc -l) )) && POWRMAX=$POWR
    (( $(echo "$FAN  > $FANMAX"  | bc -l) )) && FANMAX=$FAN
    (( $(echo "$TEDG > $TEDGMAX" | bc -l) )) && TEDGMAX=$TEDG
    (( $(echo "$TJNC > $TJNCMAX" | bc -l) )) && TJNCMAX=$TJNC
    (( $(echo "$TMEM > $TMEMMAX" | bc -l) )) && TMEMMAX=$TMEM

    buffer=$(
        clear
        echo "$CARD_NAME"
        echo -e "\nGFX Clock and Power"
        echo "SCLK: $SCLK MHz (MAX: $SCLKMAX)"
        echo "MCLK: $MCLK MHz (MAX: $MCLKMAX)"
        echo "VOLT: $VOLT mV (MAX: $VOLTMAX)"
        echo "POWR: $POWR W (MAX: $POWRMAX)"

        echo -e "\nGFX Temperature:"
        echo "FAN: $FAN RPM (MAX: $FANMAX)"
        echo "TEDG: $TEDG C (MAX: $TEDGMAX)"
        echo "TJNC: $TJNC C (MAX: $TJNCMAX)"
        echo "TMEM: $TMEM C (MAX: $TMEMMAX)"
        keyhelp
    )

    echo "$buffer"

    IFS= read -r -t $POLL -n 1 -s input && var="$input"

    case "$var" in
        q)  exit 0
            ;;
        r)  SCLKMAX=0
            MCLKMAX=0
            VOLTMAX=0
            POWRMAX=0
            FANMAX=0
            TEDGMAX=0
            TJNCMAX=0
            TMEMMAX=0
            ;;
    esac
    unset var

done
