#!/bin/sh
cat $HOME/.local/scripts/resources/font-awesome.icons | dmenu -l 10 | awk '{print $1}' | xclip -i -sel c -f | xclip -i -sel p
[ ! -z $(xclip -o -sel p) ] && notify-send "$(xclip -o -sel p) copied to clipboard"
