#!/bin/sh
cat $HOME/.local/scripts/resources/nord.colors | dmenu -l 10 | awk '{printf "%s",$2}' | xclip -i -sel c -f | xclip -i -sel p
[ ! -z $(xclip -o -sel p) ] && notify-send "$(xclip -o -sel p) copied to clipboard"
