#!/bin/sh
# Wrapper for i3lock, see man i3lock for options
# pass -c option to dispaly wallpaper only

text_color=#eceff4ff
back_color=#2e3440cc
error_color=#bf616acc
ring_color=#8fbcbbff
transparent=#00000000
highlight=#d8dee9ff
backspace=#2e3440ff

if ! [ -z $1 ] && [ $1 = "-c" ] ; then
    i3lock -k -i $HOME/.local/share/wallpaper \
    --indicator \
    --line-uses-inside \
    --ring-width 5 \
    --pass-media-keys \
    --timecolor=${text_color} \
    --datecolor=${text_color} \
    --insidecolor=${back_color} \
    --insidevercolor=${transparent} \
    --insidewrongcolor=${error_color} \
    --ringcolor=${ring_color} \
    --ringvercolor=${transparent} \
    --ringwrongcolor=${transparent} \
    --keyhlcolor=${highlight} \
    --bshlcolor=${backspace} \
    --verifcolor=${transparent} \
    --wrongcolor=${transparent} \
    --separatorcolor=${transparent}
else
    i3lock -k -B1 \
    --indicator \
    --line-uses-inside \
    --ring-width 5 \
    --pass-media-keys \
    --timecolor=${text_color} \
    --datecolor=${text_color} \
    --insidecolor=${back_color} \
    --insidevercolor=${transparent} \
    --insidewrongcolor=${error_color} \
    --ringcolor=${ring_color} \
    --ringvercolor=${transparent} \
    --ringwrongcolor=${transparent} \
    --keyhlcolor=${highlight} \
    --bshlcolor=${backspace} \
    --verifcolor=${transparent} \
    --wrongcolor=${transparent} \
    --separatorcolor=${transparent}
fi
