#!/bin/sh

options="\
logout
refresh dwm
reboot
shutdown"

choice="$(echo "$options" | dmenu | cut -f 1 -d ' ')" || exit 1

case $choice in
    logout)
        kill -TERM $(pidof s dwm)
        ;;
    refresh)
        kill -HUP $(pidof s dwm)
        ;;
    reboot)
        reboot
        ;;
    shutdown)
        poweroff
        ;;
esac
