#!/bin/sh

if ! [ -z $1 ] && [ -f $1 ] ; then
    image=$(realpath $1)
    convert "$image" -resize $HOME/.local/share/wallpaper
    #ln -sf $(realpath $1) $HOME/.local/share/wallpaper
fi

feh --no-fehbg --bg-scale $HOME/.local/share/wallpaper
